---
title: "TS1"
author: "styuk"
date: "2023-09-27"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 状態空間モデルの時系列分析

-   このノートは個人的な学習のために作成されたノートです。

-   このノートではHagiwara Junichiro先生のTime Series Analysis for the State-Space Model with R/Stanで紹介されている分析を個人的に関心のあるデータに適用しながら追っています。


```{r}
Nile
```

```{r}
plot(Nile)
```

```{r}
# Load the data
Ryori <- read.csv("CO2.csv")

# Cast the data to ts class, truncating it by December 2014
y_all <- ts(data = Ryori$CO2, start = c(1987, 1), frequency = 12)
y <- window(y_all, end = c(2014, 12))

# Display data contents
y
```


```{r}
Nile2 <- ts(Nile, start=1866)
ts.union(Nile, Nile2)
```

```{r}
 Nile2 <- 2 * Nile
 ts.plot(cbind(Nile, Nile2), ylab = "y",lty = c("solid", "dashed"))
```

```{r}
tsp(Nile)
time(Nile)
```

```{r}
day <- as.Date("2000-01-01")
str(day)

days <- seq(from = as.Date("2000-01-01"), to = as.Date("2000-01-31"), by="day")

days
weekdays(days)
```

```{r}
oldpar <- par(no.readonly=TRUE)
par(mfrow=c(2,2), oma=c(0,0,0,0), mar=c(5, 3.5, 2, 1), mgp=c(2.5, 1, 0))


plot(Nile)
title(sub="(a)", line=4, family = "mono")

y_CO2 <- y
plot(y_CO2)
title(sub = "(b)", line=4, family="mono")

plot(UKgas)
title(sub="(c)", line=4, family="mono")

load("BenchmarkNonLinearModel.RData")
y_nonlinear<-ts(y)
plot(y_nonlinear)
title(sub="(d)", line=4, family="mono")

par(oldpar)
```


```{r}
oldpar <- par(no.readonly=TRUE)
par(mfrow=c(2,2), oma=c(0,0,0,0), mar=c(5, 3.5, 2, 1), mgp=c(2.5, 1, 0))

hist(Nile, main="", xlab="データ値")
title(sub="(a)", line=4, family="mono")
summary(Nile)

hist(y_CO2, main="", xlab="データ値")
title(sub="(b)", line=4, family="mono")
summary(y_CO2)

UKgas_log <- log(UKgas)
hist(UKgas_log, main="", xlab="データ値")
title(sub="(c)", line=4, family="mono")
summary(UKgas_log)

hist(y_nonlinear, main="", xlab="データ値")
title(sub="(d)", line=4, family="mono")
summary(y_nonlinear)

par(oldpar)

```


```{r}
NA.point<-which(is.na(y_CO2))

y_CO2[NA.point]<-(y_CO2[NA.point-1]+y_CO2[NA.point+1])/2
```

```{r}
oldpar<-par(no.readonly=TRUE)
par(mfrow=c(2,2), oma=c(0,0,0,0), mar=c(5, 3.5, 2, 1), mgp=c(2.5,1,0))

acf(Nile, main="")
title(sub="(a)", line=4, family="mono")

acf(y_CO2, main="")
title(sub="(b)", line=4, family="mono")

acf(UKgas_log, main="")
title(sub="(c)", line=4, family="mono")

acf(y_nonlinear, main="")
title(sub="(d)", line=4, family="mono")

par(oldpar)
```

```{r}
acf(stock_ts, main="")
```


```{r}
plot.spectrum <- function(dat, lab="", sub="", y_max=1, tick=c(8, 4), unit=1){
  #データの周波数領域への変換
  dat_FFT <- abs(fft(as.vector(dat)))
  
  #横軸(周波数)に関する表示設定の準備
  data_len <- length(dat_FFT)
  freq_tick <- c(data_len, tick, 2)
  
  #周波数領域でデータをプロット
  plot(dat_FFT/max(dat_FFT), type="l", main="",
       ylab="|Standardized frequency spectrum|",
       ylim=c(0, y_max),
       xlab=sprintf("Frequency (1/%s)", lab),
       xlim=c(1, data_len/2), xaxt="n")
  title(sub=sub, line=4, family="mono")
  axis(side=1, at=data_len/freq_tick*unit+1,
       labels=sprintf("1/%d", freq_tick), cex.axis=0.7)
}

  #プロットの準備
  oldpar <- par(no.readonly =TRUE)
  par(mfrow=c(2,2), oma=c(0,0,0,0), mar=c(5, 3.5,
                                          2, 1), mgp=c(2.5, 1, 0))

  plot.spectrum(Nile, lab="Year", sub="(a)")  
  
  plot.spectrum(y_CO2, lab="Month", sub="(b)",tick=c(12,6))
  
  plot.spectrum(UKgas_log, lab="Month", sub="(b)",tick=c(12,6),unit=3)
  
  plot.spectrum(y_nonlinear, lab="Time point", sub="(d)")
  
  
```







```{r}
#ARモデルのWienerフィルターとカルマンフィルター
#平滑化
#ライブラリの読み込み
set.seed(42)
library(dlm)

#状態空間モデルの設定
w <- 1
v <- 2
#ARモデルの係数
phi <- 0.98
mod <- dlmModPoly(order=1, dW=w, dV=v, C0=100)
mod$GG[1, 1] <- phi


#カルマン予測を使用して観測値を生成
t_max <- 100
sim_data <- dlmForecast(mod = mod, nAhead = t_max, sampleNew = 1)
y <- sim_data$newObs[[1]]


#カルマン平滑化
dlmSmoothed_obj <- dlmSmooth(y=y, mod=mod)
s <- dropFirst(dlmSmoothed_obj$s)


#Wiener平滑化
#係数の設定
r <- v/w
b <- 1/(r*phi) + 1/phi + phi
beta <- (b - sqrt(b^2 - 4))/2

#有限の観測地の前後に最低限必要なダミーの0を補完
y_expand <- c(rep(0, t_max-1), y, rep(0, t_max-1))

#Wiener平滑化の実行
d <- (1/phi - beta)*(phi - beta)/(1-beta^2)*
  filter(method="convolution",
         filter=beta^abs(-(t_max-1):(t_max-1)),x=y_expand
         )

#結果からダミーのNAを削除
d <- d[!is.na(d)]

#結果のプロット
ts.plot(cbind(y, d, s),
        lty = c("solid","dashed","solid"),
        col = c("lightgray", "red", "blue"),
        ylab = "")

#Legend
legend(legend=c("observations", "Winner smoothing", "Kalman smoothing"),
       lty = c("solid", "dashed", "solid"),
       col = c("lightgray", "red", "blue"),
       x = "topright", text.width = 17, cex = 0.6)



```


```{r}
#ARモデルのWienerフィルターとカルマンフィルター
#平滑化
#ライブラリの読み込み
set.seed(42)
library(dlm)

#状態空間モデルの設定
w <- 1
v <- 2
#ARモデルの係数
phi <- 0.98
mod <- dlmModPoly(order=1, dW=w, dV=v, C0=100)
mod$GG[1, 1] <- phi

#カルマン予測を使用して観測値を生成
t_max <- 100
sim_data <- dlmForecast(mod = mod, nAhead = t_max, sampleNew = 1)
y <- sim_data$newObs[[1]]

#カルマン平滑化
dlmSmoothed_obj <- dlmSmooth(y=y, mod=mod)  # 修正
s <- dropFirst(dlmSmoothed_obj$s)

#Wiener平滑化
#係数の設定
r <- v/w
b <- 1/(r*phi) + 1/phi + phi
beta <- (b - sqrt(b^2 - 4))/2

#有限の観測地の前後に最低限必要なダミーの0を補完
y_expand <- c(rep(0, t_max-1), y, rep(0, t_max-1))

#Wiener平滑化の実行
d <- (1/phi - beta)*(phi - beta)/(1-beta^2) *  # 修正
  filter(method="convolution",
         filter=beta^abs(-(t_max-1):(t_max-1)),x=y_expand
  )

#結果からダミーのNAを削除
d <- d[!is.na(d)]

#結果のプロット
ts.plot(cbind(y, d, s),
        lty = c(1, 2, 1),  # 修正
        col = c("lightgray", "red", "blue"),
        ylab = "")

#Legend
legend(legend=c("observations", "Winner smoothing", "Kalman smoothing"),
       lty = c(1, 2, 1),  # 修正
       col = c("lightgray", "red", "blue"),
       x = "topright", text.width = 17, cex = 0.6)

```


```{r}

y <- Nile 
t_max <- length(y)

kalman_filtering <- function(m_t_minus1, C_t_minus_1, t) {
  
  a_t <- G_t %*% m_t_minus_1
  R_t <- G_t %*% C_t_minus_1 %*% t(G_t) + W_t
  
  f_t <- F_t %*% R
}
```






































































































































## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
